#ifndef POMELO_VERSION_H
#define POMELO_VERSION_H

#define POMELO_VERSION_MAJOR 0
#define POMELO_VERSION_MINOR 0
#define POMELO_VERSION_PATCH 1

#define POMELO_VERSION_STRING "0.0.1"

#endif // POMELO_VERSION_H
